### ISSUE TITLE
options[:source_vms] is required but not documented as such to instantiate a template

### ISSUE THREAD

**Issue by josvazg** [xlab-si/fog-vcloud-director#40]
https://github.com/xlab-si/fog-vcloud-director/blob/cc95906b4ce888bb729cf27dd3d5e88b0fc78046/lib/fog/vcloud_director/requests/compute/instantiate_vapp_template.rb#L70
^ That line is executed no matter what, so if you do something like this as the documentation suggests:
```
template.instantiate('webserver', {
  vdc_id: "9a06a16b-12c6-44dc-aee1-06aa52262ea3",
  network_id: "d5f47bbf-de27-4cf5-aaaa-56772f2ccd17"
}
```
You will get an error such as this:
```
NoMethodError: undefined method `each_with_index' for nil:NilClass
...
```

I am guessing the best fix for this will be to add this code in the `populate_uris` method in the same [source file](https://github.com/xlab-si/fog-vcloud-director/blob/cc95906b4ce888bb729cf27dd3d5e88b0fc78046/lib/fog/vcloud_director/requests/compute/instantiate_vapp_template.rb#L39):
```
          options[:endpoint] = end_point
          options[:source_vms] = [] unless options.key?(:source_vms)
          options
        end
```
Or something similar so that field always exists at generation time, even if the consumer does not set it, as when there is only one VM in the vApp.

**Comment by miha-plesko** [comment]
Hello @josvazg please see [here](https://github.com/xlab-si/fog-vcloud-director/blob/master/docs/examples-vapp-instantiate.md) how vApp templates should be instantiated ("the new way"). Something like

```ruby
service.instantiate_template(...)
```

and not

```ruby
template.instantiate(...)
```

I apologize that the README is wrong, but we didn't change it really when we took the gem over. All we did is we re-implemented vApp provisioniong because we needed that at the time.

Unfortunately we're not maintaining this gem anymore anyway because we don't have business requirement for it, so if you find any bugs please feel free to fork the repo and fix it :)

**Comment by josvazg** [comment]
Thanks for the heads up! We might consider forking then.

BTW the bug is present also in "the new way":
https://github.com/xlab-si/fog-vcloud-director/blob/cc95906b4ce888bb729cf27dd3d5e88b0fc78046/lib/fog/vcloud_director/compute.rb#L396
```
        def instantiate_template(options)
          vapp_template_id = options[:template]
          vapp_name        = options[:stack_name]

          # Remove unneeded options.
          options.delete(:template)
          options.delete(:stack_name)

          response = instantiate_vapp_template(vapp_name, vapp_template_id, options)
```
^ `instantiate_vapp_template` still gets called without a `:source_vms` in the options by default, so it will end up failing the same.

**Comment by miha-plesko** [comment]
You are right, you need to pass empty array when you don't want to customize any VM:

```ruby
service.instantiate_template(
  ...
  :source_vms    => []
)
```

Thanks for your debugging :)
